#!/usr/bin/env python3
"""Stand in for a serial target on the far end of the GPIO channel.

The loopback jumper makes the Flipper its own target, so the reply is
byte-identical to what it just sent and arrives at its own clock. That
leaves three things untested: receiving across an independent clock,
storing bytes the kit did not generate, and the listen-window logic
against a target with real latency.

This listens on a USB-TTL adapter, prints whatever the kit transmits, and
replies with text of its own — which is what makes it a real target
rather than an echo.

    # Watch only, no reply
    python3 tools/gpio_target_sim.py --port /dev/cu.usbserial-XXXX

    # Reply once the kit stops sending
    python3 tools/gpio_target_sim.py --port /dev/cu.usbserial-XXXX \\
        --reply "ACME-HMI v2.1 ready. System prompt: you are a helpful assistant."

    # Reply with more than the kit's 512-byte capture buffer, to exercise
    # the truncation path
    python3 tools/gpio_target_sim.py --port /dev/cu.usbserial-XXXX --reply-bytes 700

Wiring is crossed, and the adapter must be 3.3V:

    adapter RX  -> Flipper pin 13 (TX)
    adapter TX  -> Flipper pin 14 (RX)
    adapter GND -> Flipper pin 18 (GND)

Remove the 13->14 loopback jumper first, or the Flipper's own echo masks
the reply. Run the Flipper on battery: with both devices on one laptop
the grounds are already common through USB, and the probe ground makes a
loop that corrupts the line.

Check the adapter before blaming the wiring. Short its own RX and TX
together, with the Flipper disconnected, and run this script with any
--reply: a healthy adapter immediately sees its own traffic.

Do this first. An adapter that transmits but cannot receive looks exactly
like bad wiring, and one of ours was precisely that — it enumerated,
bound its driver on both macOS and Linux, accepted stty and accepted
writes, and never returned a single byte even shorted to itself. Hours
went into rewiring the Flipper before the self-loop was tried.

FTDI FT232R and Silicon Labs CP2102 are the safe choices. Prolific
0x067B:0x2303 clones are additionally rejected by Apple's driver, which
is a separate problem that can mask this one.
"""

import argparse
import sys
import time

import serial


def render(data: bytes, limit: int = 2000) -> str:
    """Show control characters rather than letting them move the cursor —
    a payload containing \\r would otherwise overwrite the output."""
    out = []
    for byte in data[:limit]:
        if byte == 0x0A:
            out.append("\\n")
        elif byte == 0x0D:
            out.append("\\r")
        elif byte == 0x09:
            out.append("\\t")
        elif byte < 0x20 or byte >= 0x7F:
            out.append(f"\\x{byte:02x}")
        else:
            out.append(chr(byte))
    return "".join(out) + ("..." if len(data) > limit else "")


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--port", required=True, help="USB-TTL device node")
    ap.add_argument("--baud", type=int, default=115200)
    ap.add_argument("--reply", help="text to send back after the kit stops sending")
    ap.add_argument("--reply-bytes", type=int,
                    help="instead of --reply, send this many generated bytes")
    ap.add_argument("--reply-delay-ms", type=int, default=50,
                    help="wait this long after the last received byte before "
                         "replying, so the reply lands inside the listen window "
                         "rather than colliding with the transmission")
    ap.add_argument("--idle-ms", type=int, default=300,
                    help="silence that marks the end of a transmission")
    ap.add_argument("--timeout", type=int, default=120,
                    help="give up after this many seconds with nothing received")
    args = ap.parse_args()

    reply = None
    if args.reply_bytes:
        # Numbered so truncation is obvious: if the kit keeps the first N
        # bytes you can read off exactly where it stopped.
        chunk = "".join(f"[{i:04d}]" for i in range(args.reply_bytes // 6 + 2))
        reply = chunk[: args.reply_bytes].encode()
    elif args.reply:
        reply = args.reply.encode() + b"\n"

    with serial.Serial(args.port, args.baud, timeout=0.05) as ser:
        ser.reset_input_buffer()
        print(f"listening on {args.port} at {args.baud} 8N1")
        if reply:
            print(f"will reply with {len(reply)} bytes, "
                  f"{args.reply_delay_ms} ms after the kit goes quiet")
        else:
            print("watch-only, will not reply")
        print("trigger a send on the Flipper (Ctrl+C to stop)\n")

        buf = bytearray()
        last_rx = None
        started = time.monotonic()
        transmissions = 0

        try:
            while True:
                data = ser.read(4096)
                now = time.monotonic()

                if data:
                    # Discard self-interference.  TX and RX run side by
                    # side in an unshielded jumper bundle, so a fast burst
                    # on one couples into the other: sending 700 bytes at
                    # 115200 reliably produces a handful of NULs on our
                    # own RX.  Left alone those satisfy the
                    # start-of-transmission test below, and the reply
                    # they trigger produces more of them — the simulator
                    # answers itself in a loop and never sees the kit.
                    #
                    # A real payload is text.  A burst that is entirely
                    # NUL, on a line we were just driving, is ours.
                    if set(data) <= {0}:
                        continue

                    if not buf:
                        print(f"[{now - started:7.2f}s] receiving...")
                    buf += data
                    last_rx = now
                    continue

                # Idle. If we were mid-transmission and it has been quiet
                # long enough, the transmission is over.
                if buf and last_rx and (now - last_rx) * 1000 >= args.idle_ms:
                    transmissions += 1
                    print(f"[{now - started:7.2f}s] received {len(buf)} bytes:")
                    print(f"    {render(bytes(buf))}")

                    if reply:
                        time.sleep(args.reply_delay_ms / 1000.0)
                        ser.write(reply)
                        ser.flush()
                        print(f"[{time.monotonic() - started:7.2f}s] "
                              f"replied with {len(reply)} bytes")
                        # Drop whatever our own transmission coupled back
                        # into RX.  The NUL filter above already ignores
                        # it, but clearing here keeps the buffer honest
                        # and means a genuine reply from the kit is not
                        # queued behind our own noise.  We cannot hear
                        # the kit while transmitting anyway.
                        ser.reset_input_buffer()
                    print()
                    buf.clear()
                    last_rx = None

                if not buf and last_rx is None and (now - started) > args.timeout:
                    if transmissions == 0:
                        print(f"nothing received in {args.timeout}s.")
                        print("Check: jumper removed, wiring crossed "
                              "(adapter RX to Flipper TX), baud matches "
                              "Settings > GPIO Baud.")
                        return 1
                    return 0

        except KeyboardInterrupt:
            print(f"\nstopped after {transmissions} transmission(s)")
            return 0 if transmissions else 1


if __name__ == "__main__":
    sys.exit(main())
